global:
  scrape_interval: 5s # By default, scrape targets every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: "mintwit-monitor"

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "minitwit-simulator"
    static_configs:
      - targets: ["simulator-api:5001"]
        labels:
          group: "production"
