name: Deployment

on:
  push:
    branches:
      - master

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Push backend to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dagandersen/backend
        username: ${{ secrets.DOCKER_DAG_TEST_USER }}
        password: ${{ secrets.DOCKER_DAG_TEST_PASSWORD }}
        workdir: backend
    - uses: actions/checkout@master
    - name: Push frontend to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dagandersen/frontend
        username: ${{ secrets.DOCKER_DAG_TEST_USER }}
        password: ${{ secrets.DOCKER_DAG_TEST_PASSWORD }}
        workdir: frontend

    - uses: actions/checkout@master
    - name: Copy files via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.server_ip }}
        USERNAME: ${{ secrets.server_user }}
        KEY: ${{ secrets.CI_private_key }}
      with:
        source: "."
        target: "/vagrant/"

    - name: Docker-Compose Pull and Up
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.server_ip }}
        USERNAME: ${{ secrets.server_user }}
        KEY: ${{ secrets.CI_private_key }}
        script: |
          cd /vagrant/
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull 
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tagger
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: true

    - name: Checkout code
      uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ steps.tagger.outputs.new_tag }}
        release_name: Release ${{ steps.tagger.outputs.new_tag }}
        body: |
          This release was automatically generated by workflow: ${{ github.workflow }}
        draft: true
        prerelease: false