name: Scheduled simulator-test on prod

on:
  push:
    branches:
      - scheduledPythonTest

jobs:
  simulator-test:
    name: simulator-test on server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        cd tests/scheduled_test/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        bash test