name: Scheduled simulator-test on prod

on:
  schedule:
    - cron:  '*/5 * * * *' # Check runs every 12th hour

jobs:
  simulator-test:
    name: simulator-test on server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        cd tests/schedualed_test/
        python -m pip install --upgrade pip
        pip install
        bash test